"""
migrate_mssql_to_pg.py — Pull data from SQL Server, push to PostgreSQL.
SQL Server is the SOURCE OF TRUTH — all tables and all columns are migrated.

Usage:
    python migrations/migrate_mssql_to_pg.py \
        --src "mssql+pymssql://user:pass@host/db" \
        --dst "postgresql://user:pass@host:port/db" \
        [--tables tblMenu tblNews ...]   # migrate only these tables (default: all)
        [--truncate]                     # truncate PG tables before insert

What this script does:
  1. Reads ALL tables + ALL columns from SQL Server (source of truth)
  2. Creates tables in PostgreSQL using SQL Server schema (not SQLAlchemy models)
     - Preserves all columns including those not in models (Views, SEON, etc.)
     - Maps SQL Server types → PostgreSQL types
     - Adds IDENTITY columns as GENERATED BY DEFAULT AS IDENTITY
  3. Copies all data in 500-row batches
  4. Post-migration:
     - Converts JSONB-compatible columns (WebsiteInfo)
     - Normalizes tblLink.RowUrl to lowercase + creates LOWER() indexes
     - Resets all sequences to MAX(id)
"""

import argparse
import sys
import os
import time
from urllib.parse import unquote

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

import pymssql
import psycopg2
import psycopg2.extras

BATCH_SIZE = 500

# Table migration order (parents before children to respect FK if any)
ALL_TABLES = [
    "tblTotal",
    "tblMenu",
    "tblTag",
    "tblUser",
    "tblPermissions",
    "tblLink",
    "tblNews",
    "tblPro",
    "tblAdvert",
    "tblContact",
    "tblURL",
    "tblComment",
    "tblIntro",
    "tblTab",
    "tblVideo",
    "tblLangM",  # models/lang.py maps this
]

# ── Connection helpers ────────────────────────────────────────────────────────

def parse_mssql_url(url: str) -> dict:
    rest = url.replace("mssql+pymssql://", "")
    userpass, hostdb = rest.split("@", 1)
    user, password = userpass.split(":", 1)
    host, db = hostdb.split("/", 1)
    return dict(server=host, user=user, password=unquote(password), database=db, timeout=30)


def parse_pg_url(url: str) -> dict:
    rest = url.replace("postgresql://", "")
    userpass, hostdb = rest.split("@", 1)
    user, password = userpass.split(":", 1)
    if "/" in hostdb:
        hostport, db = hostdb.split("/", 1)
    else:
        hostport, db = hostdb, ""
    host, port = (hostport.split(":", 1) if ":" in hostport else (hostport, "5432"))
    return dict(host=host, port=int(port), user=user, password=unquote(password), dbname=db)


# ── Type mapping: SQL Server → PostgreSQL DDL ─────────────────────────────────

def ms_type_to_pg(data_type: str, char_max: int | None, num_prec: int | None,
                  num_scale: int | None, is_identity: bool) -> str:
    t = data_type.lower()

    if is_identity:
        return "INTEGER GENERATED BY DEFAULT AS IDENTITY"

    if t in ("nvarchar", "varchar"):
        if char_max == -1 or char_max is None:
            return "TEXT"
        return f"VARCHAR({char_max})"
    if t in ("nchar", "char"):
        return f"CHAR({char_max})" if char_max else "CHAR(1)"
    if t in ("ntext", "text", "xml"):
        return "TEXT"
    if t == "int":
        return "INTEGER"
    if t == "bigint":
        return "BIGINT"
    if t == "smallint":
        return "SMALLINT"
    if t == "tinyint":
        return "SMALLINT"
    if t == "bit":
        return "INTEGER"   # store as int, pymssql returns bool — coerced in _coerce_row
    if t in ("datetime", "datetime2", "smalldatetime"):
        return "TIMESTAMP"
    if t == "date":
        return "DATE"
    if t == "time":
        return "TIME"
    if t in ("decimal", "numeric"):
        if num_prec is not None:
            return f"NUMERIC({num_prec},{num_scale or 0})"
        return "NUMERIC"
    if t in ("float", "real"):
        return "DOUBLE PRECISION"
    if t == "money":
        return "NUMERIC(19,4)"
    if t == "uniqueidentifier":
        return "UUID"
    if t in ("varbinary", "binary", "image"):
        return "BYTEA"
    return "TEXT"  # fallback


# ── Get full SQL Server schema ────────────────────────────────────────────────

def get_ms_tables(ms_cur) -> list[str]:
    ms_cur.execute(
        "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES "
        "WHERE TABLE_TYPE='BASE TABLE' AND TABLE_SCHEMA='dbo' ORDER BY TABLE_NAME"
    )
    return [r[0] for r in ms_cur.fetchall()]


def get_ms_schema(ms_cur, table: str) -> list[dict]:
    """Return list of column dicts for a SQL Server table."""
    ms_cur.execute("""
        SELECT
            c.COLUMN_NAME,
            c.DATA_TYPE,
            c.CHARACTER_MAXIMUM_LENGTH,
            c.NUMERIC_PRECISION,
            c.NUMERIC_SCALE,
            c.IS_NULLABLE,
            c.COLUMN_DEFAULT,
            COLUMNPROPERTY(OBJECT_ID(%s), c.COLUMN_NAME, 'IsIdentity') AS is_identity,
            c.ORDINAL_POSITION
        FROM INFORMATION_SCHEMA.COLUMNS c
        WHERE TABLE_NAME = %s AND TABLE_SCHEMA = 'dbo'
        ORDER BY ORDINAL_POSITION
    """, (table, table))
    cols = []
    for r in ms_cur.fetchall():
        cols.append({
            "name": r[0],
            "data_type": r[1],
            "char_max": r[2],
            "num_prec": r[3],
            "num_scale": r[4],
            "nullable": r[5] == "YES",
            "default": r[6],
            "is_identity": bool(r[7]),
            "position": r[8],
        })
    return cols


def get_ms_pk(ms_cur, table: str) -> list[str]:
    ms_cur.execute("""
        SELECT ku.COLUMN_NAME
        FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
        JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE ku
          ON tc.CONSTRAINT_NAME = ku.CONSTRAINT_NAME
        WHERE tc.TABLE_NAME = %s AND tc.CONSTRAINT_TYPE = 'PRIMARY KEY'
        ORDER BY ku.ORDINAL_POSITION
    """, (table,))
    return [r[0] for r in ms_cur.fetchall()]


# ── Create table in PostgreSQL ────────────────────────────────────────────────

def create_pg_table(pg_cur, table: str, columns: list[dict], pk_cols: list[str]):
    col_defs = []
    for c in columns:
        pg_type = ms_type_to_pg(
            c["data_type"], c["char_max"], c["num_prec"], c["num_scale"], c["is_identity"]
        )
        null_clause = "" if c["nullable"] else " NOT NULL"
        col_defs.append(f'  "{c["name"]}" {pg_type}{null_clause}')

    if pk_cols:
        pk_str = ", ".join(f'"{c}"' for c in pk_cols)
        col_defs.append(f"  PRIMARY KEY ({pk_str})")

    ddl = f'CREATE TABLE IF NOT EXISTS "{table}" (\n' + ",\n".join(col_defs) + "\n);"
    pg_cur.execute(ddl)


# ── Data helpers ──────────────────────────────────────────────────────────────

def get_ms_row_count(ms_cur, table: str) -> int:
    ms_cur.execute(f'SELECT COUNT(*) FROM [{table}]')
    return ms_cur.fetchone()[0]


def fetch_ms_rows(ms_cur, table: str, columns: list[str], offset: int, limit: int):
    col_list = ", ".join(f"[{c}]" for c in columns)
    ms_cur.execute(
        f"SELECT {col_list} FROM [{table}] "
        f"ORDER BY (SELECT NULL) "
        f"OFFSET {offset} ROWS FETCH NEXT {limit} ROWS ONLY"
    )
    return ms_cur.fetchall()


def _coerce_row(row: dict) -> dict:
    """Fix type mismatches: bool→int (BIT columns), bytes→str where safe."""
    return {
        k: (int(v) if isinstance(v, bool) else v)
        for k, v in row.items()
    }


# ── Post-migration fixes ──────────────────────────────────────────────────────

def convert_webinfo_to_jsonb(pg_cur, pg_conn):
    """Convert tblTotal.WebsiteInfo from TEXT to JSONB if stored as JSON string."""
    pg_cur.execute("""
        SELECT data_type FROM information_schema.columns
        WHERE table_name='tblTotal' AND column_name='WebsiteInfo'
    """)
    row = pg_cur.fetchone()
    if not row:
        return
    if row[0].lower() in ("text", "character varying"):
        pg_cur.execute("""
            ALTER TABLE "tblTotal"
            ALTER COLUMN "WebsiteInfo" TYPE JSONB
            USING CASE WHEN "WebsiteInfo" IS NULL OR "WebsiteInfo" = ''
                  THEN NULL ELSE "WebsiteInfo"::jsonb END
        """)
        pg_conn.commit()
        print("  + tblTotal.WebsiteInfo converted TEXT → JSONB")


def create_extra_tables(pg_cur, pg_conn):
    """
    Create tables that don't exist in SQL Server but are needed by python-admin.
    - tblLangM: mirror of tblMenu for language-2 (English) navigation tree
    """
    pg_cur.execute("""
        CREATE TABLE IF NOT EXISTS "tblLangM" (
          "IDM"         VARCHAR(10)  NOT NULL,
          "AutoM"       INTEGER      GENERATED BY DEFAULT AS IDENTITY,
          "NameM"       VARCHAR(200),
          "Name1M"      VARCHAR(100),
          "TypeM"       INTEGER      DEFAULT 1,
          "Levels"      INTEGER      DEFAULT 1,
          "SortM"       VARCHAR(10)  DEFAULT '00',
          "AcM"         INTEGER      DEFAULT 1,
          "Lang"        INTEGER      DEFAULT 2,
          "NameMH"      VARCHAR(200),
          "URL"         VARCHAR(100),
          "HomeM"       INTEGER,
          "DescM"       TEXT,
          "title"       VARCHAR(200),
          "keywords"    VARCHAR(100),
          "description" VARCHAR(300),
          "ischema"     TEXT,
          "Rel"         VARCHAR(100),
          "ChkM"        INTEGER,
          "TabM"        VARCHAR(20),
          PRIMARY KEY ("IDM")
        )
    """)
    pg_conn.commit()
    print("  + tblLangM created (language-2 menu tree)")


def create_performance_indexes(pg_cur, pg_conn):
    """
    Create indexes recommended in python-admin but not present in SQL Server.
    - ix_tblURL_active_old: speeds up 301 redirect lookup in every request
    """
    pg_cur.execute(
        'CREATE INDEX IF NOT EXISTS ix_tblurl_active_old ON "tblURL" ("Url_Ac", "Url_Old")'
    )
    pg_conn.commit()
    print("  + ix_tblURL_active_old created")


def normalize_slugs(pg_cur, pg_conn):
    """Lowercase tblLink.RowUrl and create LOWER() functional indexes."""
    pg_cur.execute('UPDATE "tblLink" SET "RowUrl" = LOWER("RowUrl") WHERE "RowUrl" != LOWER("RowUrl")')
    pg_cur.execute(
        'CREATE INDEX IF NOT EXISTS ix_tbllink_rowurl_lower ON "tblLink" (LOWER("RowUrl"))'
    )
    pg_cur.execute(
        'CREATE INDEX IF NOT EXISTS ix_tblmenu_slug_lower ON "tblMenu" (LOWER("Name1M"))'
    )
    pg_cur.execute(
        'CREATE INDEX IF NOT EXISTS ix_tblnews_slug_lower ON "tblNews" (LOWER("Name1N"))'
    )
    pg_conn.commit()
    print("  + Slug normalization + LOWER() indexes done")


def reset_sequences(pg_cur, pg_conn, tables: list[str], ms_cur):
    """Reset every IDENTITY-derived sequence to MAX(col) to prevent INSERT conflicts."""
    for table in tables:
        ms_cur.execute("""
            SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_NAME = %s AND TABLE_SCHEMA = 'dbo'
              AND COLUMNPROPERTY(OBJECT_ID(%s), COLUMN_NAME, 'IsIdentity') = 1
        """, (table, table))
        id_cols = [r[0] for r in ms_cur.fetchall()]
        for col in id_cols:
            seq = f'"{table}_{col}_seq"'
            try:
                pg_cur.execute(f'SELECT MAX("{col}") FROM "{table}"')
                max_val = pg_cur.fetchone()[0] or 0
                pg_cur.execute(f"SELECT setval({seq!r}, %s, true)", (max(max_val, 1),))
                pg_conn.commit()
                print(f"  + Sequence {table}.{col} reset to {max(max_val, 1)}")
            except Exception as e:
                pg_conn.rollback()
                print(f"  ~ Sequence {table}.{col}: {e}")


# ── Main migration ────────────────────────────────────────────────────────────

def migrate_table(ms_cur, pg_cur, pg_conn, table: str, schema: list[dict],
                  pk_cols: list[str], truncate: bool):
    col_names = [c["name"] for c in schema]
    total = get_ms_row_count(ms_cur, table)
    print(f"  {table}: {total} rows", end="", flush=True)

    if truncate:
        pg_cur.execute(f'TRUNCATE TABLE "{table}" RESTART IDENTITY CASCADE')
        pg_conn.commit()

    col_list_pg = ", ".join(f'"{c}"' for c in col_names)
    # Use %s placeholders for psycopg2
    placeholders = ", ".join(["%s"] * len(col_names))
    # IDENTITY columns need OVERRIDING SYSTEM VALUE when inserting explicit values
    identity_cols = {c["name"] for c in schema if c["is_identity"]}
    if identity_cols:
        insert_sql = (
            f'INSERT INTO "{table}" ({col_list_pg}) '
            f'OVERRIDING SYSTEM VALUE VALUES ({placeholders})'
        )
    else:
        insert_sql = f'INSERT INTO "{table}" ({col_list_pg}) VALUES ({placeholders})'

    inserted = 0
    offset = 0
    while offset < total:
        rows = fetch_ms_rows(ms_cur, table, col_names, offset, BATCH_SIZE)
        if not rows:
            break
        coerced = [tuple(_coerce_row(dict(zip(col_names, row))).values()) for row in rows]
        psycopg2.extras.execute_batch(pg_cur, insert_sql, coerced, page_size=BATCH_SIZE)
        pg_conn.commit()
        inserted += len(rows)
        offset += BATCH_SIZE
        print(f"\r  {table}: {inserted}/{total}", end="", flush=True)

    print(f"\r  {table}: {inserted}/{total} rows ✓")


def main():
    parser = argparse.ArgumentParser(description="Migrate SQL Server → PostgreSQL (SQL Server is source of truth)")
    parser.add_argument("--src", required=True, help="SQL Server URL (mssql+pymssql://...)")
    parser.add_argument("--dst", required=True, help="PostgreSQL URL (postgresql://...)")
    parser.add_argument("--tables", nargs="+", default=None, help="Migrate only these tables")
    parser.add_argument("--truncate", action="store_true", help="Truncate PG tables before insert")
    args = parser.parse_args()

    # ── Connect ───────────────────────────────────────────────────────────────
    print("Connecting to SQL Server...")
    ms_conn = pymssql.connect(**parse_mssql_url(args.src))
    ms_cur = ms_conn.cursor()
    print("  OK")

    print("Connecting to PostgreSQL...")
    pg_conn = psycopg2.connect(**parse_pg_url(args.dst))
    pg_conn.autocommit = False
    pg_cur = pg_conn.cursor()
    print("  OK")

    # ── Discover tables ───────────────────────────────────────────────────────
    ms_all_tables = get_ms_tables(ms_cur)
    tables_to_migrate = args.tables or [t for t in ALL_TABLES if t in ms_all_tables]
    # Add any SQL Server tables not in ALL_TABLES list
    for t in ms_all_tables:
        if t not in tables_to_migrate:
            tables_to_migrate.append(t)

    print(f"\nSQL Server has {len(ms_all_tables)} tables, migrating {len(tables_to_migrate)}")

    # ── Create tables from SQL Server schema ──────────────────────────────────
    print("\nCreating tables in PostgreSQL (from SQL Server schema)...")
    for table in tables_to_migrate:
        schema = get_ms_schema(ms_cur, table)
        pk_cols = get_ms_pk(ms_cur, table)
        if not schema:
            print(f"  ! {table}: no columns in SQL Server, skipping")
            continue
        try:
            create_pg_table(pg_cur, table, schema, pk_cols)
            pg_conn.commit()
            print(f"  + {table} ({len(schema)} cols, PK={pk_cols})")
        except Exception as e:
            pg_conn.rollback()
            print(f"  ! {table}: CREATE failed — {e}")

    # ── Migrate data ──────────────────────────────────────────────────────────
    print(f"\nMigrating data ({len(tables_to_migrate)} tables)...")
    start = time.time()
    for table in tables_to_migrate:
        schema = get_ms_schema(ms_cur, table)
        pk_cols = get_ms_pk(ms_cur, table)
        if not schema:
            continue
        try:
            migrate_table(ms_cur, pg_cur, pg_conn, table, schema, pk_cols, args.truncate)
        except Exception as e:
            pg_conn.rollback()
            print(f"\n  ERROR {table}: {e}")

    # ── Post-migration ────────────────────────────────────────────────────────
    print("\nPost-migration fixes...")
    convert_webinfo_to_jsonb(pg_cur, pg_conn)
    create_extra_tables(pg_cur, pg_conn)
    create_performance_indexes(pg_cur, pg_conn)
    normalize_slugs(pg_cur, pg_conn)
    reset_sequences(pg_cur, pg_conn, tables_to_migrate, ms_cur)

    elapsed = time.time() - start
    print(f"\nDone in {elapsed:.1f}s")

    ms_conn.close()
    pg_conn.close()


if __name__ == "__main__":
    main()
